<p>
  <b>BARTOC Skosmos</b> is a terminology service for vocabularies not easily available
  via other services. See <a href="https://bartoc.org/registries/">BARTOC registries</a>
  for a comprehensive list of terminology services, registries, and repositories.
</p>
<p>
  BARTOC Skosmos was first developed and hosted at UB Basel and is being transferred to
  VZG in 2023. It is currently in <em>beta development</em> so please expect instability!
</p>
